language: go
sudo: required
go:
- 1.13.x
dist: trusty
addons:
  sonarcloud:
    organization: paysuper
stages:
- test
- name: deploy
  if: branch = develop
jobs:
  include:
  - stage: test
    services:
    - rabbitmq
    cache:
      directories:
        - $GOPATH/pkg/mod    
    install: true
    script:
    - go test ./... -coverprofile=coverage.out -covermode=atomic -p=1
    after_success:
    - bash <(curl -s https://codecov.io/bash)
  - stage: deploy
    services: docker
    install: true
    script:
    - docker run -it -e JENKINS_AUTH_TOKEN=$JENKINS_AUTH_TOKEN -e JENKINS_BUILD_TOKEN=$JENKINS_BUILD_TOKEN
      -e JENKINS_BUILD_PROJECT=$TRAVIS_REPO_SLUG -e JENKINS_BUILD_BRANCH=$TRAVIS_BRANCH
      p1hub/p1jenkinstrigger
notifications:
  email: false
  slack:
    secure: Sd3bD1yeBhLIBYtkBXD0CXrCZJZTrKOT3r0OreWCoXg4YuXMAeI1nwyoQjD8sRaGfkgh4dl3629RJcyWzXMlg5eRkeDPxqa2/wpTm/P+cKig/mnXGNeMBMBWnn9cyHAmuQ+ZmoXzNDqnxOQCfVRSy5SzrDKm9KPTf1E8Dh3BxN7DVEL2HRgE+ODxSJ8eNADHKfdQt7gXSZigHtrnA8QYnko1lct++Mg77aahUtAtk1N057/LA5CG+ptcBrA2gxrlbODnEPdycLOIL5xx4hFpcuriGRVsBUtmdi5wdVu7Nx32ys5tIGHl5ik5Qc2Tj3P9x3h0i2+BOaGK1YjCtu/c4dXs4yKFy2Okx3IIfCzZdSMvk4hyYPKe8dxoRbrmrlxqrigXeD8NHx1uZEp2e2yTr4CQWy8erlw3elzaGRNp3Rw+5Mb/NLqoa21YrkwTcUPYELYB1XYJga5zL17J7Dmzh9JBPLYWio8//hD743wVBC9AbBBhQMo5PkO6DmTeymSIZMNT/hFT2aFvn6nmwx4PXuUao6LPt86i2xq8XynusEQxMkI0/g793I7SYYxB2IrKd+YjG3RgK8QVKYy15xpq3YuD00Dhjr6CFMGnVPLSEk8H+OfnfRj2Mt1IhzBmbLUCrRmAjS0O9kjkWVVmxcaI1neeETd3++4O4C9xCQu/vqo=
env:
  global:
  - GO111MODULE=on
  - secure: tDWVN3enlA5Zmk0arlMmhxWCRC8gfTycqiIhboQR9/LY3H3i5l85J4HG4josJNIQCFeqAIbR66f1PMBdzKuSVIdziGNfH600wUiQEsVYWvtZK8UKa2jFEid/egDreK4vJ5Csv85u/zxw47FEAYvHClkVpGzlCxTogyLK7bbkx5xW15M342pwNDO8fD4ybXKdxwiyzDGNGTa2fEPUM43xWxuHr+i2RxPqZ8GwjZ6LzBrxVSYCXZPpsxlsvjZhDS67w82xxWdvFbqULinB8jayV47XvADlEqMwGkqpBsK817o94yQ8jd8xrgj2V7G+bd5dkHbo1GAELn8kB53sd4hpxEMAWgERQV3iShAV2FK3TjtQLBacDjjUlE2ncHu/05K8ceeUZ6PAhiCPVsu/QAl8xmtSTVCtaZvLLLszxXnTA9Km56FPL1Z6yXmZzt4+xdwgiP/L1TGEsVM9/JkXIFxW98hPjQDkFBACJisAWphOWwwkPSDJI9X9lItu98JyklAJWCqrfyrbFqTM+RE2Df3+heEasXyXKuFDZAqGjgcs0j8R52XJAbf0J2a50VGvQAX2VgfEU+Ku958DSvuSPAnnkaTuq0yzSihNh1eGA8K/O1AK4YxtuVCWvidafEvDTPuuFyP7vrG2hgkNJ5WKnRSaJJwAcyULhtFwmCZ3WizceqM=
  - secure: FRnbMiwp5EVLN5eBOC7cUjDxNqukalQLhUjaEH3RFMhUbmstJLjjcEtWGfKY4LbsqTcwX9WBNRJ+8825eex1vdtMqnfMsaZ3NY058L0sl2KPkqEaUI1IeMwy9zp2tRByUYqoLQzfXGZElHfKoa+iEx5U/b7CdLW3YvriUmEeQcSpaDE6sYy8wai6D4+6nT/kEc1Ogg6U/czlqzgpown81+igvLedgSCTQbCD5FealM+egdTf7StHaggKfO2KBkI28RoZCTeb8edYArQWm3AkzP6Drqtz7aVT+at2pAGCGuxBj0KNvma/mvZdR4A96BLq8toeyRayEjtH8tDTZffLzkm4/CTESAvQl6ziZXo0OGrGDz8MkAmkqtv4yKA+ZC2/IG4Daka5Cj+6mgkh8ASKo43CKBoB2YnImLtPH723neu0wtDn9Gy/nE8p73cmZiOOw5pb953xPoXHZDaHHg4+FXnYIvxGRGWz8e/jo1pnND2HAwRgxPcbO9NjKDbe1S960ZOkwnUFYsIudQzzXJ0t/gUP21eu1jstiW/zUjF94z/JqyYibUbud50HiVKzzUD+mRph0iriue4COwn0mzLtspe9WB1zuLRYdmXgHIJGAEliR7SdQkna3cBZelpormxUALZFnhvqdttESuJ3uT6iPnsFYLu0ubS/1X9KRpslCuM=
  - secure: vfobTBO8kk6DQQYApapjjeMRcqI7PVn8t6pFxVCUy4MgJOKUS9dBZSyrouC0b9yPRRuOKQ21gTSx7ck+4YaWP7j1kGO/kjT+ZcxU7q3/fF82aDH1ISRHXBNT/1gHz1hBQLrIzDkCppy2Xl4mZnRZEd4X5YChXyl1u4xDobmEj7sutL01JeM2KA95T8zAdMM2ZxjefWhtJJ0kwCWdbv0vt3s2sW0lnt1JN/hlpeiD1iVaQZ+ceBMIdgJRGMgP5+gIspA3OqCKLqV/oZrkDY3QHPuNAIYakMpsCmimErEfEAKaicPHELVX7W9tJvuZDBS/jy7iX5+VxUouNbK3UdK5FpjsWhgpRdXo/Tjt/vXm0rEAiVaKdXFUHKvAkL07a8YIUmmzEA6lbi6TmCbLOY7ACbQclQRsvHBH39EBJkCb+wpXFGb7fumKW+XuNit3EIoAwqczrooVa40Rvunhid3KUQsBeyY+UbxGTE6KD52iUkv0UlKNKYHHpSSrNuzkO6wQN5BegHsoqOJwS4haN5MB4V5WNRw307HSvM0otDUZH4vqRyzjhpRW2ao9IU4sv98kOX9Jo+Yp/iyncFYT3Paqb1xz9ICVZQKkF1MsA1EaQy6umw4lDuzEjwD7X2oTV8i0g3gk/dePifzbPaBaXP58Uy9Q94vMelKrNFEhbJ7QCps=
