protoc:
  version: 3.9.1
  includes:
    - pkg

generate:
  go_options:
    import_path: github.com/paysuper/postmark-sender

  plugins:
    - name: go
      type: go
      flags: paths=source_relative
      output: pkg